version: 2
project_name: tn3270proxy

before:
  hooks:
    - go mod tidy

builds:
  - id: tn3270proxy
    main: ./cmd/tn3270proxy
    binary: tn3270proxy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "tn3270proxy_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE.md
      - README.md
      - tn3270proxy.example.json

checksum:
  name_template: "SHA256SUMS"
  algorithm: sha256

changelog:
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: Documentation
      regexp: '^.*?docs(\(.+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  prerelease: auto
